### ISSUE TITLE
builder 3.0.0 release includes a 3MB tags file

### ISSUE THREAD

**Issue by drbrain** [jimweirich/builder#10] opened 2011-10-17 22:31 UTC
The TAGS file is 97% of the contents of the gem and just wastes space:

```
$ gem contents builder
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/CHANGES
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/README
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/README.rdoc
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/Rakefile
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/TAGS
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/doc/releases/builder-1.2.4.rdoc
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/doc/releases/builder-2.0.0.rdoc
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/doc/releases/builder-2.1.1.rdoc
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/lib/blankslate.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/lib/builder.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/lib/builder/blankslate.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/lib/builder/xchar.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/lib/builder/xmlbase.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/lib/builder/xmlevents.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/lib/builder/xmlmarkup.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/test/performance.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/test/preload.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/test/test_blankslate.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/test/test_cssbuilder.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/test/test_eventbuilder.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/test/test_markupbuilder.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/test/test_namecollision.rb
/Library/Ruby/Gems/1.8/gems/builder-3.0.0/test/test_xchar.rb
$ du -hcd1 /Library/Ruby/Gems/1.8/gems/builder-3.0.0
 12K    /Library/Ruby/Gems/1.8/gems/builder-3.0.0/doc
 44K    /Library/Ruby/Gems/1.8/gems/builder-3.0.0/lib
 48K    /Library/Ruby/Gems/1.8/gems/builder-3.0.0/test
2.9M    /Library/Ruby/Gems/1.8/gems/builder-3.0.0
2.9M    total
$ du -h /Library/Ruby/Gems/1.8/gems/builder-3.0.0/TAGS
2.8M    /Library/Ruby/Gems/1.8/gems/builder-3.0.0/TAGS
```

**Comment by drbrain** [comment] 2011-10-18 20:45
See also:

https://github.com/rdoc/rdoc/issues/81

https://github.com/rails/rails/issues/3322

**Comment by karlin** [comment] 2011-12-22 20:57
Pretty sure this was caused by a greedy '[A-Z]*' file glob in the rdoc_files list. Fixed by https://github.com/jimweirich/builder/pull/14

**Comment by jimweirich** [comment] 2012-09-06 21:46
Fixed for next release.

**Closed as completed by jimweirich** 2012-09-06 21:46 UTC
